apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/vol/mongo-vol"
