apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cinder: 
    volumeID: "c50eca2c-e7f7-405b-b268-983874b26cdb"
